### ISSUE TITLE
Why service is dealing with view changes?

### ISSUE THREAD

**Issue by adrianpawlik** [Bubuhubu87/bc-jokes#2]
https://github.com/Bubuhubu87/bc-jokes/blob/28f5380d823112e6014773dbe4c4d93695f31daa/jokes/src/app/modules/jokes/components/notification-bar/notification.service.ts#L16

**Comment by Bubuhubu87** [comment]
Notification component is introduced in app.component.html, and Notification service can be injected in every possible component. That approach give us flexibility to use success/failure notification.

Could you give me better idea to improve that solution?

**Comment by Bubuhubu87** [comment]
To be done with stream from service to component then component will take responsibility for rendering view.

**Comment by Bubuhubu87** [comment]
Done
