### ISSUE TITLE
API URL could be injected and store in the environmental configuration

### ISSUE THREAD

**Issue by adrianpawlik** [Bubuhubu87/bc-jokes#4]
https://github.com/Bubuhubu87/bc-jokes/blob/28f5380d823112e6014773dbe4c4d93695f31daa/jokes/src/app/modules/jokes/services/jokes.service.ts#L16

**Comment by Bubuhubu87** [comment]
Good point, to fix.

**Comment by Bubuhubu87** [comment]
Done
