### ISSUE TITLE
Why are the properties capitalised? 

### ISSUE THREAD

**Issue by adrianpawlik** [Bubuhubu87/bc-jokes#5]
https://github.com/Bubuhubu87/bc-jokes/blob/28f5380d823112e6014773dbe4c4d93695f31daa/jokes/src/app/modules/jokes/models/joke.model.ts#L2

**Comment by Bubuhubu87** [comment]
To easier recognize difference between properties and arguments. I know that we have "this." (to be determine)

**Comment by Bubuhubu87** [comment]
fixed
