### ISSUE TITLE
Message service does not work properly

### ISSUE THREAD

**Issue by adrianpawlik** [Bubuhubu87/bc-jokes#7]
After switching in between categories and displaying a few jokes in a row, on a new screen all messages are being displayed.

**Comment by Bubuhubu87** [comment]
I will check it, thanks.

**Comment by Bubuhubu87** [comment]
changing observer initialization to constructor with first() operator
`this.observableSwitchMap = this.dataSharedService.currentMessage.pipe(
first(),
            switchMap((category: Category) => this.JokesService.getRandomJokeBy(category)));`

and unsubscribe in getRandomJoke

`this.subscription$ = this.observableSwitchMap.subscribe((result: Joke) => {
            this.fetchJoke(result);
            this.subscription$.unsubscribe();
        },`

do the job.

Problem is in creation subscriber every time when we hit the button. To fix.

**Comment by Bubuhubu87** [comment]
Fixed
